package main

import (
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// config is the on-disk settings file at ~/.alfred/config.yaml.
type config struct {
	Provider   provider `yaml:"provider"`
	ClaudeHost string   `yaml:"claude_host"`
	OpenAIHost string   `yaml:"openai_host"`

	// OpenAIAzureEndpoint switches the OpenAI client to Azure OpenAI when
	// set (taking precedence over OpenAIHost). Auth still comes from the
	// ALFRED_API_KEY environment variable, never from this file.
	OpenAIAzureEndpoint   string `yaml:"openai_azure_endpoint"`
	OpenAIAzureAPIVersion string `yaml:"openai_azure_api_version"`

	// ImageViewer, if set, is run (as "<image_viewer> <path>") to open an
	// image generated by :image after it's saved to disk.
	ImageViewer string `yaml:"image_viewer"`

	// SessionRetentionDays, if > 0, causes session files not touched in
	// that many days to be deleted on startup. 0 (the default) keeps
	// history forever.
	SessionRetentionDays int `yaml:"session_retention_days"`
}

// loadConfig reads ~/.alfred/config.yaml. A missing file is not an error -
// it just means the defaults apply.
func loadConfig() (config, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return config{}, err
	}
	data, err := os.ReadFile(filepath.Join(home, ".alfred", "config.yaml"))
	if err != nil {
		if os.IsNotExist(err) {
			return config{}, nil
		}
		return config{}, err
	}
	var cfg config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return config{}, err
	}
	return cfg, nil
}
